#!/usr/bin/env python3
"""
Generate parameter-specific static FEC codec wrappers with constant Vandermonde matrices.
"""

from __future__ import annotations

import pathlib
import sys
from typing import Iterable

import numpy as np

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from matrix.vandermonde import Van

# (m, k, data_width, packets)
COMBOS: Iterable[tuple[int, int, int, list[int]]] = [
    (3, 5, 10, [0, 3, 4]),
    (5, 8, 10, [0, 3, 5, 6, 7]),
    (8, 12, 10, [0, 4, 6, 7, 8, 9, 10, 11]),
]


def format_matrix(matrix: np.ndarray, width: int) -> str:
    rows = []
    for row in matrix:
        elems = ", ".join(f"{width}'d{int(val)}" for val in row)
        rows.append(f"'{{{elems}}}")
    return "'{\n    " + ",\n    ".join(rows) + "\n  }"


def write_module(m: int, k: int, data_width: int, packets: list[int], out_path: pathlib.Path) -> None:
    full_width = data_width + 1  # parity lifted width used inside fec_codec

    van = Van(m=m, k=k, order=full_width - 1)
    decode = van.invert(packets)  # shape (m, m)
    encode = van.M[:, packets]    # shape (m, m)

    module_name = f"fec_codec_static_m{m}_k{k}_w{data_width}"

    decode_literal = format_matrix(decode, full_width)
    encode_literal = format_matrix(encode, full_width)

    symbols_unpack = "\n  ".join(
        [
            f"assign symbols_in[{idx}] = symbols_in_flat[{idx * data_width + data_width - 1}:{idx * data_width}];"
            for idx in range(m)
        ]
    )
    symbols_pack = "\n  ".join(
        [
            f"assign symbols_out_flat[{idx * data_width + data_width - 1}:{idx * data_width}] = symbols_out[{idx}];"
            for idx in range(m)
        ]
    )

    content = f"""// Auto-generated by scripts/generate_static_fec.py
`timescale 1ns / 1ps

module {module_name} (
  input  logic [{m * data_width - 1}:0] symbols_in_flat,
  output logic [{m * data_width - 1}:0] symbols_out_flat
);
  localparam int M = {m};
  localparam int WIDTH = {full_width};
  localparam int DATA_W = {data_width};

  localparam logic [WIDTH-1:0] DECODE_MATRIX [M][M] = {decode_literal};
  localparam logic [WIDTH-1:0] ENCODE_MATRIX [M][M] = {encode_literal};

  logic [DATA_W-1:0] symbols_in [M];
  logic [DATA_W-1:0] symbols_out[M];

  {symbols_unpack}

  fec_codec #(
    .M(M),
    .WIDTH(WIDTH)
  ) u_codec (
    .symbols_in     (symbols_in),
    .decode_coeffs  (DECODE_MATRIX),
    .encode_coeffs  (ENCODE_MATRIX),
    .symbols_out    (symbols_out),
    .lifted_symbols (),
    .decoded_symbols(),
    .encoded_symbols()
  );

  {symbols_pack}
endmodule
"""
    out_path.write_text(content, encoding="utf-8")


def main() -> None:
    generated_dir = pathlib.Path("verilog/generated")
    generated_dir.mkdir(parents=True, exist_ok=True)

    for m, k, data_width, packets in COMBOS:
        filename = generated_dir / f"fec_codec_static_m{m}_k{k}_w{data_width}.sv"
        write_module(m, k, data_width, packets, filename)
        print(f"Generated {filename}")


if __name__ == "__main__":
    main()
